// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connector struct {
	ID          string `json:"id"`
	LocationID  string `json:"LocationId"`
	Type        string `json:"Type"`
	ChargeSpeed string `json:"ChargeSpeed"`
	Active      bool   `json:"Active"`
}

type NewConnector struct {
	LocationID  string `json:"LocationId"`
	Type        string `json:"Type"`
	ChargeSpeed string `json:"ChargeSpeed"`
	Active      bool   `json:"Active"`
}
