// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connector struct {
	ID          string `json:"id"`
	StationID   int    `json:"StationID"`
	Type        string `json:"Type"`
	ChargeSpeed string `json:"ChargeSpeed"`
	Active      bool   `json:"Active"`
}

type NewConnector struct {
	StationID   int    `json:"StationID"`
	Type        string `json:"Type"`
	ChargeSpeed string `json:"ChargeSpeed"`
	Active      bool   `json:"Active"`
}
